language: node_js
node_js:
  - "10.19.0"
script:
  - npm install
install:
  - npm install -g firebase-tools
  - npm install @material-ui/core
  - npm install @material-ui/icons
  - npm install @material-ui/lab
  - npm install react-router-dom
after_success:
  - firebase deploy --token $FIREBASE_TOKEN